### ISSUE TITLE
Unable to harvest/repair clothing add by mod

### ISSUE THREAD

**Issue by GamingWubba93** [TheDevv/Prison-Pack#2]
Not sure if this is intentional, but I am unable to breakdown or repair any of the clothing added by this mod.

**Comment by GamingWubba93** [comment]
Read up on Behaviour JSON Documentation from https://ds5678.github.io/ModComponent/index.html to fix the issue I was having where clothing from this mod was not repairable or harvestable. Decided to patch the clothing.

Patched changes can be found in my pull request located here: [https://github.com/GamingWubba93/Prison-Pack/pulls](url)

**Comment by TheDevv** [comment]
> Not sure if this is intentional, but I am unable to breakdown or repair any of the clothing added by this mod.

I forgot ot add the,. Thank you for the pull request!
